# Generated by Django 2.1.7 on 2019-03-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
        ('loans', '0002_auto_20190308_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_num', models.CharField(max_length=255, unique=True)),
                ('principal', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.LoanAccount')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.PositiveIntegerField()),
                ('loan_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.LoanIssue')),
            ],
        ),
        migrations.CreateModel(
            name='SavingDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.SavingAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SavingWithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.SavingAccount')),
            ],
        ),
    ]
