# Generated by Django 2.1.7 on 2019-03-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavingWithdrawl',
            new_name='SavingWithdrawal',
        ),
    ]
