# Generated by Django 2.1.7 on 2019-03-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_loanissue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanissue',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=15),
        ),
    ]
