# Generated by Django 2.1.7 on 2019-03-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_loanpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanpayment',
            old_name='amount',
            new_name='account',
        ),
    ]
